name: Build & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: ğŸ“¥ Get latest source code
        uses: actions/checkout@v2
      - name: ğŸ“¦ Install npm packages and setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --silent
      - name: ğŸ§ª Testing using @testing-library/react-hooks
        uses: actions/setup-node@v2
      - run: npm run test
      - name: ğŸ—ï¸ Build using Rollup.js
        uses: actions/setup-node@v2
      - run: npm run build
      - name: ğŸšš NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
